#!/bin/bash

str="URL\nSearch"
choice=$(echo -e $str | dmenu -i -p 'SEARCH: ')

if [[ $choice = '' ]]; then
  exit
else
  if [[ $choice = 'URL' ]]; then
    search=$(cat bookmarks.txt | dmenu -i -p 'URL SEARCH: ')

    if [[ ${search} = '' ]]; then
      exit
    else
      sh ${BROWSER} ${search}
    fi
  else
    look=$(echo 'Cancel' | dmenu -i -p 'TUXI SEARCH: ')

    if [[ $look = 'Cancel' ]]; then
      exit
    elif [[ ${look} = '' ]]; then
      exit
    else
      lookup=$(tuxi $look)
      echo $lookup
    fi
  fi
fi
