#!/bin/bash

pac=$(find / -name pacman.conf  2>/dev/null | sed '/find/ d ; /etc/ d ; /.cargo/ d')
diffs=$(diff $pac /etc/pacman.conf)
Diffs=($diffs)
if [ "$Diffs" != "" ]
then
  echo "
Do you want to replace default pacman.conf?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) sudo rm -rf /etc/pacman.conf ; sudo cp $pac /etc/ ; break;;
        No ) break;;
    esac
  done
else
  echo "
pacman.conf is to your specs,"
  echo "Nothing to do...
  "
fi



gitisthere=$(cd $HOME ; git remote show origin | grep "Fetch")

if [ "$gitisthere" != "  Fetch URL: https://github.com/TheArk99/Arch-dot-files.git" ]
then
  echo "
dot files are Not installed, do You want to install them?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) cd $HOME
          git clone https://github.com/TheArk99/Arch-dot-files.git &
          cp -a Arch-dot-files/. $HOME ;
          rm -rf $HOME/Arch-dot-files ;
          echo "
whould You like to install all apps from the installed-apps.txt?" ;
          select yn in "Yes" "No"; do
            case $yn in
              Yes ) pacman -Syu --needed $(comm -12 <(pacman -Slq | sort) <(sort ~/installed-apps.txt)) --noconfirm ;
                cd $HOME ;
                git clone https://aur.archlinux.org/paru.git ;
                cd $HOME/paru ;
                makepkg -si &
                paru -Syu --needed - < ~/installed-apps.txt --noconfirm ;
                break;;
              No ) break;;
            esac
          done
          break;;
        No ) break;;
    esac
  done
else
  echo "
You have Arch-dot-files already installed,"
  echo "Nothing to do...
  "
fi


#installs wallpappers
if [[ ! -d $HOME/Pictures/wallpapers ]]
then
  echo "
wallpappers are not installed, do you wan to install them?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) cd $HOME/Pictures/
          git clone https://github.com/TheArk99/wallpappers.git &
          break;;
        No ) break;;
    esac
  done
else
  echo "
Your wallpappers are already installed,"
  echo "Nothing to do...
  "
fi

#chooses the wallpapper
if [[ ! -f $HOME/.cache/wal/colors-wal-dwm.h ]]
then
  ranger $HOME/Pictures/wallpappers/ &
else
  echo "
Wal is set,"
  echo "Nothing to do...
  "
fi


if [[ ! -d $HOME/.config/dwm ]]
then
  echo "
dwm is Not installed, do You want to install it?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) cd $HOME/.config/
          git clone https://github.com/TheArk99/dwm.git &
          cd $HOME/.config/dwm/ ;
          sudo make clean install &
          echo "dwm is Now installed" ;
          break;;
        No ) break;;
    esac
  done
else
  echo "
You have dwm already installed,"
  echo "Nothing to do...
  "
fi


if [[ ! -d $HOME/.config/slstatus ]]
then
  echo "
slstatus is Not installed, do You want to install it?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) cd $HOME/.config/
          git clone https://github.com/TheArk99/slstatus.git &
          cd $HOME/.config/slstatus ;
          sudo ln pacmanUpgrades /bin/ &
          sudo ln forecast /bin/ &
          sudo ln moonphase /bin/ &
          sudo make clean install &
          echo "slstatus is Now installed" ;
          break;;
        No ) break;;
    esac
  done
else
  echo "
You have slstatus already installed,"
  echo "Nothing to do...
  "
fi


if [[ ! -d $HOME/.config/dmenu ]]
then
  echo "
dmenu is Not installed, do You want to install it?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) cd $HOME/.config
          git clone https://github.com/TheArk99/dmenu.git ${home}/.config/ &
          cd $HOME/.config/dmenu ;
          sudo make clean install &
          echo "dmenu is Now installed" ;
          break;;
        No ) break;;
    esac
  done
else
  echo "
You have dmenu already installed,"
  echo "Nothing to do...
  "
fi

#installs fonts for the system
fontgit=$(cd /etc/fonts/ ; git remote show origin | grep "Fetch")
if [ "$fontgit" != "  Fetch URL: https://github.com/TheArk99/fonts.git" ]
then
  echo "
fonts are not installed, do You want to install them?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) cd /etc/
          sudo git clone https://github.com/TheArk99/fonts.git &
          fc-cache -f -v ;
          break;;
        No ) break;;
    esac
  done
else
  echo "
Your fonts are installed,"
  echo "Nothing to do...
  "
fi


#installs the git repo of extensions for urxvt to make it usable
if [[ ! -f /lib64/urxvt/perl/resize-font ]]
then
  echo "
urxvt extensions are Not installed, do You want to install them?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) cd /lib64/urxt/
          sudo git clone https://github.com/TheArk99/URxvt-perl-extensions.git &
          sudo rm -rf perl/* &
          sudo cp -a URxvt-perl-extensions/. /lib64/urxvt/perl/ &
          sudo rm -rf /lib64/urxvt/URxvt-perl-extensions ;
          break;;
        No ) break;;
    esac
  done
else
  echo "
You have URxvt-extenstions already installed,"
  echo "Nothing to do...
  "
fi
