#!/bin/bash

home='/home/*'

pac=$(find / -name pacman.conf  2>/dev/null | sed '/find/ d ; /etc/ d ; /.cargo/ d')
diffs=$(diff $pac /etc/pacman.conf)
Diffs=($diffs)
if [ "$Diffs" != "" ]
then
  echo "
Do you want to replace default pacman.conf?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) rm -rf /etc/pacman.conf ; cp $pac /etc/ ; break;;
        No ) break;;
    esac
  done
else
  echo "
pacman.conf is to your specs,"
  echo "Nothing to do...
  "
fi

sleep 5

gitisthere=$(cd $home ; git remote show origin | grep "Fetch")

if [ "$gitisthere" != "  Fetch URL: https://github.com/TheArk99/Arch-dot-files.git" ]
then
  echo "
dot files are Not installed, do You want to install them?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) cd $home/
          git clone https://github.com/TheArk99/Arch-dot-files.git &
          sleep 15
          cp -a Arch-dot-files/. $home/ &
          sleep 5
          rm -rf $home/Arch-dot-files ;
          echo "
whould You like to install all apps from the installed-apps.txt?" ;
          select yn in "Yes" "No"; do
            case $yn in
              Yes ) cd $home/
                pacman -Syu --needed $(comm -12 <(pacman -Slq | sort) <(sort ~/installed-apps.txt)) --noconfirm &
                sleep 15
                git clone https://aur.archlinux.org/paru.git &
                cd $home/paru ;
                makepkg -si &
                sleep 10
                paru -Syu --needed - < ~/installed-apps.txt --noconfirm &
                sleep 15
                break;;
              No ) break;;
            esac
          done
          break;;
        No ) break;;
    esac
  done
else
  echo "
You have Arch-dot-files already installed,"
  echo "Nothing to do...
  "
fi


sleep 5

#installs wallpappers
if [[ ! -d $home/Pictures/wallpapers ]]
then
  echo "
wallpappers are not installed, do you wan to install them?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) cd $home/Pictures/
          git clone https://github.com/TheArk99/wallpappers.git &
          break;;
        No ) break;;
    esac
  done
else
  echo "
Your wallpappers are already installed,"
  echo "Nothing to do...
  "
fi

sleep 5

#chooses the wallpapper
if [[ ! -f $home/.cache/wal/colors-wal-dwm.h ]]
then
  ranger $home/Pictures/wallpappers/ &
else
  echo "
Wal is set,"
  echo "Nothing to do...
  "
fi

sleep 5


if [[ ! -d $home/.config/dwm ]]
then
  echo "
dwm is Not installed, do You want to install it?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) cd $home/.config/
          git clone https://github.com/TheArk99/dwm.git &
          cd $home/.config/dwm/ ;
          make clean install &
          echo "dwm is Now installed" ;
          break;;
        No ) break;;
    esac
  done
else
  echo "
You have dwm already installed,"
  echo "Nothing to do...
  "
fi


sleep 5

if [[ ! -d $home/.config/slstatus ]]
then
  echo "
slstatus is Not installed, do You want to install it?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) cd $home/.config/
          git clone https://github.com/TheArk99/slstatus.git &
          cd $home/.config/slstatus ;
          ln pacmanUpgrades /bin/ &
          ln forecast /bin/ &
          ln moonphase /bin/ &
          make clean install &
          echo "slstatus is Now installed" ;
          break;;
        No ) break;;
    esac
  done
else
  echo "
You have slstatus already installed,"
  echo "Nothing to do...
  "
fi


sleep 5


if [[ ! -d $home/.config/dmenu ]]
then
  echo "
dmenu is Not installed, do You want to install it?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) cd $home/.config
          git clone https://github.com/TheArk99/dmenu.git ${home}/.config/ &
          cd $home/.config/dmenu ;
          sudo make clean install &
          echo "dmenu is Now installed" ;
          break;;
        No ) break;;
    esac
  done
else
  echo "
You have dmenu already installed,"
  echo "Nothing to do...
  "
fi


sleep 5

#installs fonts for the system
fontgit=$(cd /etc/fonts/ ; git remote show origin | grep "Fetch")
if [ "$fontgit" != "  Fetch URL: https://github.com/TheArk99/fonts.git" ]
then
  echo "
fonts are not installed, do You want to install them?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) cd /etc/
          git clone https://github.com/TheArk99/fonts.git &
          fc-cache -f -v ;
          break;;
        No ) break;;
    esac
  done
else
  echo "
Your fonts are installed,"
  echo "Nothing to do...
  "
fi

sleep 5


#installs the git repo of extensions for urxvt to make it usable
if [[ ! -f /lib64/urxvt/perl/resize-font ]]
then
  echo "
urxvt extensions are Not installed, do You want to install them?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) cd /lib64/urxt/
          git clone https://github.com/TheArk99/URxvt-perl-extensions.git &
          rm -rf perl/* &
          cp -a URxvt-perl-extensions/. /lib64/urxvt/perl/ &
          rm -rf /lib64/urxvt/URxvt-perl-extensions ;
          break;;
        No ) break;;
    esac
  done
else
  echo "
You have URxvt-extenstions already installed,"
  echo "Nothing to do...
  "
fi
