#!/bin/bash

#this should be able to ask user for time and distance and then give back how fast the object was

#echo "waht was the distance include units but with a space away from numbers"
#read dist
dist="60 m"
distNo=$(echo $dist | cut -d " " -f1)


echo "what was the time include units with a space away from numbes" &&
read time &&
timeNo=$(echo $time | cut -d " " -f1)

speed=$(echo ${distNo}"/"${timeNo} | bc)
units(){
  distU=$(echo $dist | cut -d " " -f2)
  timeU=$(echo $time | cut -d " " -f2)
  echo $distU"/"$timeU
}
echo $units
printf "This was the speed...${speed} %s"units
