#!/bin/bash

#this script when run will print out what the class of a program is when the program is clicked with mouse

xprop | awk '
        /^WM_CLASS/{sub(/.* =/, "instance:"); sub(/,/, "\nclass:"); print}
        /^WM_NAME/{sub(/.* =/, "title:"); print}'
