#!/bin/sh
dwm="/home/noah/.config/dwm/"
dmenu="/home/noah/.config/dmenu/"
stat="/home/noah/.config/slstatus"
make="make clean install"

cd $dwm &&
doas $make;
cd $dmenu &&
doas $make;
cd $stat &&
doas $make
