#!/bin/sh
dwm="/home/noah/.config/dwm/"
dmenu="/home/noah/.config/dmenu/"
stat="/home/noah/.config/slstatus"
make="make clean install"

cd $dwm &&
  sudo $make || exit;

cd $dmenu &&
  sudo $make || exit;

cd $stat &&
  sudo $make || exit
