#!/bin/sh
dir='/home/'$USER'/Documents/scripts/'

options=$(cd ${dir} && find  -maxdepth 1 -type f | sed 's/^..//' | cut -d " " -f1)
arr=($options)

choice=$(echo -e "${options[@]}" | dmenu -i -p 'scritps: ')

permisions=$(stat -c %A ${dir}${choice})
echo "$per"
if [ "$permisions" != "-rwxr-xr-x" ]; then
  chmod +x ${dir}${choice}
  urxvt -e ${dir}${choice}
fi

urxvt -e ${dir}${choice}
