#!/bin/sh
dir='/home/'$USER'/Documents/scripts/'

options=$(cd ${dir} && /bin/ls -d * | cut -d " " -f1)
arr=($options)

choice=$(echo -e "${options[@]}" | dmenu -i -p 'scritps: ')

permisions=$(stat -c %A ${dir}${choice})
per=($permisions)
echo "$per"
if [ "$per" != "-rwxr-xr-x" ]; then
  chmod +x ${dir}${choice}
fi

urxvt -e ${dir}${choice}
