#! /bin/bash

myDir='/home/'$USER'/Documents/school/'
options=$(cd ${myDir} && /bin/ls -d */)
arr=($options)

choice=$(echo -e "${options[@]}" | dmenu -i -p 'School: ')
echo $choice
dir="$myDir""$choice"
Dir=$($dir | sed 's/,//g')
bibdir="${dir}/semester\ 2/bindercheck3/"

if [ "$choice" == "${arr[6]}" ]; then
  ranger $bibdir
else
  ranger $Dir
fi
