#! /bin/bash

myDir='/home/'$USER'/Documents/school/'
options=$(cd ${myDir} && /bin/ls -d */ | cut -d " " -f1)
arr=($options)

choice=$(echo -e "${options[@]}" | dmenu -i -p 'School: ')

dir=${myDir}${choice}

if [ "$choice" == ${arr[2]} ]; then
  ranger $dir/semester\ 2/bindercheck3/
else
  ranger $dir
fi
