#! /bin/bash

myDir='/home/'$USER'/Documents/school/'
options=$(cd ${myDir} && /bin/ls -d */ | cut -d " " -f1)
arr=($options)

choice=$(echo -e "${options[@]}" | dmenu -i -p 'School: ')

#if [ "$choice" == ${arr[2]} ]; then
#  urxvt -e cd ${myDir}${choice}
#else
#  urxvt -e cd ${myDir}${choice}
#fi

dir=${myDir}${choice}
