#!/bin/sh

LOCK=""
SLEEP=""
LOGOUT=""
RESTART=""
SHUTDOWN=""

list_icons() {
    echo $LOCK
    echo $SLEEP
    echo $RESTART
    echo $SHUTDOWN
}

list_icons_PC() {
    echo $SLEEP
    echo $RESTART
    echo $SHUTDOWN
}

handle_option() {
    case "$1" in
        "$LOCK")
          slock
            ;;
        "$SLEEP")
          systemctl suspend
            ;;
        "$RESTART")
          reboot
            ;;
        "$SHUTDOWN")
          poweroff
            ;;
    esac
}

handle_option_PC() {
    case "$1" in
        "$SLEEP")
          systemctl suspend
            ;;
        "$RESTART")
          reboot
            ;;
        "$SHUTDOWN")
          poweroff
            ;;
    esac
}

if [[ ! -f /bin/slock ]]
then
  SELECTION="$(list_icons_PC | rofi -dmenu -theme options_menu)"
  handle_option_PC $SELECTION &
else
  SELECTION="$(list_icons | rofi -dmenu -theme options_menu)"
  handle_option $SELECTION &
fi
