#!/bin/bash
espeak "what would you like to talk about?" 2>/dev/null;
#PS3="what would you like to talk about?"
talks=("say hello to user" "go home" "exit")
select choice in "${talks[@]}"; do
  case $choice in
    "say hello to user")
      espeak '"hello user" $USER' 2>/dev/null;
      break;;
    "go home")
      espeak "you wish to go home and rethink your life" 2>/dev/null;
      break;;
    "exit")
      espeak "you are now exititng..." 2>/dev/null
      exit;;
    *) espeak "Invalid option $REPLY" 2>/dev/null;;
  esac
done
